// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overlock/storage/v1beta1/query.proto

package v1beta1

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryShowRegistryRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryShowRegistryRequest) Reset()         { *m = QueryShowRegistryRequest{} }
func (m *QueryShowRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowRegistryRequest) ProtoMessage()    {}
func (*QueryShowRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e5b066eaba21290, []int{0}
}
func (m *QueryShowRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowRegistryRequest.Merge(m, src)
}
func (m *QueryShowRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowRegistryRequest proto.InternalMessageInfo

func (m *QueryShowRegistryRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryShowRegistryResponse struct {
	Registry Registry `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry"`
}

func (m *QueryShowRegistryResponse) Reset()         { *m = QueryShowRegistryResponse{} }
func (m *QueryShowRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowRegistryResponse) ProtoMessage()    {}
func (*QueryShowRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e5b066eaba21290, []int{1}
}
func (m *QueryShowRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowRegistryResponse.Merge(m, src)
}
func (m *QueryShowRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowRegistryResponse proto.InternalMessageInfo

func (m *QueryShowRegistryResponse) GetRegistry() Registry {
	if m != nil {
		return m.Registry
	}
	return Registry{}
}

type QueryListRegistryRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListRegistryRequest) Reset()         { *m = QueryListRegistryRequest{} }
func (m *QueryListRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListRegistryRequest) ProtoMessage()    {}
func (*QueryListRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e5b066eaba21290, []int{2}
}
func (m *QueryListRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListRegistryRequest.Merge(m, src)
}
func (m *QueryListRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListRegistryRequest proto.InternalMessageInfo

func (m *QueryListRegistryRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListRegistryResponse struct {
	Registry   []Registry          `protobuf:"bytes,1,rep,name=registry,proto3" json:"registry"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListRegistryResponse) Reset()         { *m = QueryListRegistryResponse{} }
func (m *QueryListRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListRegistryResponse) ProtoMessage()    {}
func (*QueryListRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e5b066eaba21290, []int{3}
}
func (m *QueryListRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListRegistryResponse.Merge(m, src)
}
func (m *QueryListRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListRegistryResponse proto.InternalMessageInfo

func (m *QueryListRegistryResponse) GetRegistry() []Registry {
	if m != nil {
		return m.Registry
	}
	return nil
}

func (m *QueryListRegistryResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryShowRegistryRequest)(nil), "overlock.storage.v1beta1.QueryShowRegistryRequest")
	proto.RegisterType((*QueryShowRegistryResponse)(nil), "overlock.storage.v1beta1.QueryShowRegistryResponse")
	proto.RegisterType((*QueryListRegistryRequest)(nil), "overlock.storage.v1beta1.QueryListRegistryRequest")
	proto.RegisterType((*QueryListRegistryResponse)(nil), "overlock.storage.v1beta1.QueryListRegistryResponse")
}

func init() {
	proto.RegisterFile("overlock/storage/v1beta1/query.proto", fileDescriptor_5e5b066eaba21290)
}

var fileDescriptor_5e5b066eaba21290 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x8a, 0x13, 0x31,
	0x18, 0xc7, 0x27, 0xe3, 0x2a, 0x12, 0x17, 0xc1, 0xe0, 0xa1, 0x16, 0x99, 0xd5, 0x61, 0xd9, 0xca,
	0xa2, 0x09, 0xdb, 0x7d, 0x01, 0x59, 0x44, 0x2f, 0x1e, 0x74, 0xbc, 0xed, 0x45, 0x32, 0x9d, 0x90,
	0x86, 0x6d, 0xf3, 0xcd, 0x4e, 0xd2, 0x2d, 0x22, 0x5e, 0x7c, 0x02, 0xc1, 0x17, 0xf0, 0xe2, 0xc5,
	0x27, 0xd9, 0xe3, 0xa2, 0x17, 0x4f, 0x22, 0xad, 0x0f, 0x22, 0xcd, 0x64, 0xc6, 0x59, 0x3b, 0x43,
	0xd1, 0x4b, 0x09, 0xcd, 0xff, 0xff, 0x7d, 0xbf, 0xef, 0xff, 0x4d, 0xf0, 0x2e, 0x9c, 0x89, 0x62,
	0x02, 0xa3, 0x13, 0x66, 0x2c, 0x14, 0x5c, 0x0a, 0x76, 0x76, 0x90, 0x0a, 0xcb, 0x0f, 0xd8, 0xe9,
	0x4c, 0x14, 0x6f, 0x68, 0x5e, 0x80, 0x05, 0xd2, 0xab, 0x54, 0xd4, 0xab, 0xa8, 0x57, 0xf5, 0x6f,
	0xf1, 0xa9, 0xd2, 0xc0, 0xdc, 0x6f, 0x29, 0xee, 0xef, 0x8f, 0xc0, 0x4c, 0xc1, 0xb0, 0x94, 0x1b,
	0x51, 0x56, 0xa9, 0x6b, 0xe6, 0x5c, 0x2a, 0xcd, 0xad, 0x02, 0xed, 0xb5, 0xb7, 0x25, 0x48, 0x70,
	0x47, 0xb6, 0x3a, 0xf9, 0x7f, 0xef, 0x4a, 0x00, 0x39, 0x11, 0x8c, 0xe7, 0x8a, 0x71, 0xad, 0xc1,
	0x3a, 0x8b, 0xf1, 0xb7, 0x83, 0x4e, 0xe4, 0x42, 0x48, 0x65, 0x6c, 0x45, 0x1d, 0xef, 0xe3, 0xde,
	0xcb, 0x55, 0xfb, 0x57, 0x63, 0x98, 0x27, 0xfe, 0x2a, 0x11, 0xa7, 0x33, 0x61, 0x2c, 0xb9, 0x89,
	0x43, 0x95, 0xf5, 0xd0, 0x3d, 0xf4, 0x60, 0x2b, 0x09, 0x55, 0x16, 0x73, 0x7c, 0xa7, 0x45, 0x6b,
	0x72, 0xd0, 0x46, 0x90, 0x27, 0xf8, 0x7a, 0x55, 0xda, 0x59, 0x6e, 0x0c, 0x63, 0xda, 0x95, 0x08,
	0xad, 0xdc, 0x47, 0x5b, 0xe7, 0x3f, 0x76, 0x82, 0xa4, 0x76, 0xc6, 0xa9, 0xc7, 0x79, 0xae, 0x8c,
	0xfd, 0x1b, 0xe7, 0x29, 0xc6, 0x7f, 0xb2, 0xf1, 0x3d, 0xf6, 0x68, 0x19, 0x24, 0x5d, 0x05, 0x49,
	0xcb, 0x75, 0x54, 0x4d, 0x5e, 0x70, 0x29, 0xbc, 0x37, 0x69, 0x38, 0xe3, 0x2f, 0xc8, 0xcf, 0x71,
	0xb9, 0x49, 0xeb, 0x1c, 0x57, 0xfe, 0x6f, 0x0e, 0xf2, 0xec, 0x12, 0x6b, 0xe8, 0x58, 0x07, 0x1b,
	0x59, 0x4b, 0x84, 0x26, 0xec, 0xf0, 0x6b, 0x88, 0xaf, 0x3a, 0x58, 0xf2, 0x19, 0xe1, 0xed, 0x66,
	0xf2, 0x64, 0xd8, 0xcd, 0xd5, 0xb5, 0xd2, 0xfe, 0xe1, 0x3f, 0x79, 0x4a, 0x9e, 0xf8, 0xe1, 0xfb,
	0x6f, 0xbf, 0x3e, 0x86, 0x7b, 0x64, 0x97, 0xad, 0x7d, 0x55, 0x66, 0x0c, 0xf3, 0xd7, 0xd5, 0xd4,
	0xec, 0xad, 0xca, 0xde, 0x91, 0x4f, 0x08, 0x6f, 0x37, 0x93, 0xdd, 0xc8, 0xd9, 0xb2, 0xeb, 0x8d,
	0x9c, 0x6d, 0xab, 0x8b, 0x07, 0x8e, 0xf3, 0x3e, 0xd9, 0x59, 0xe7, 0x9c, 0x28, 0x63, 0x6b, 0xce,
	0xa3, 0xe3, 0xf3, 0x45, 0x84, 0x2e, 0x16, 0x11, 0xfa, 0xb9, 0x88, 0xd0, 0x87, 0x65, 0x14, 0x5c,
	0x2c, 0xa3, 0xe0, 0xfb, 0x32, 0x0a, 0x8e, 0x1f, 0x4b, 0x65, 0xc7, 0xb3, 0x94, 0x8e, 0x60, 0x5a,
	0x17, 0x79, 0xa4, 0x85, 0x9d, 0x43, 0x71, 0xe2, 0x9e, 0x9a, 0x04, 0xa6, 0x21, 0x13, 0xac, 0xeb,
	0x7d, 0xa5, 0xd7, 0xdc, 0xbb, 0x3a, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x11, 0xb7, 0x4b,
	0x35, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of ShowRegistry items.
	ShowRegistry(ctx context.Context, in *QueryShowRegistryRequest, opts ...grpc.CallOption) (*QueryShowRegistryResponse, error)
	// Queries a list of ListRegistry items.
	ListRegistry(ctx context.Context, in *QueryListRegistryRequest, opts ...grpc.CallOption) (*QueryListRegistryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ShowRegistry(ctx context.Context, in *QueryShowRegistryRequest, opts ...grpc.CallOption) (*QueryShowRegistryResponse, error) {
	out := new(QueryShowRegistryResponse)
	err := c.cc.Invoke(ctx, "/overlock.storage.v1beta1.Query/ShowRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListRegistry(ctx context.Context, in *QueryListRegistryRequest, opts ...grpc.CallOption) (*QueryListRegistryResponse, error) {
	out := new(QueryListRegistryResponse)
	err := c.cc.Invoke(ctx, "/overlock.storage.v1beta1.Query/ListRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of ShowRegistry items.
	ShowRegistry(context.Context, *QueryShowRegistryRequest) (*QueryShowRegistryResponse, error)
	// Queries a list of ListRegistry items.
	ListRegistry(context.Context, *QueryListRegistryRequest) (*QueryListRegistryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ShowRegistry(ctx context.Context, req *QueryShowRegistryRequest) (*QueryShowRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowRegistry not implemented")
}
func (*UnimplementedQueryServer) ListRegistry(ctx context.Context, req *QueryListRegistryRequest) (*QueryListRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRegistry not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ShowRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overlock.storage.v1beta1.Query/ShowRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowRegistry(ctx, req.(*QueryShowRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overlock.storage.v1beta1.Query/ListRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListRegistry(ctx, req.(*QueryListRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "overlock.storage.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowRegistry",
			Handler:    _Query_ShowRegistry_Handler,
		},
		{
			MethodName: "ListRegistry",
			Handler:    _Query_ListRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "overlock/storage/v1beta1/query.proto",
}

func (m *QueryShowRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Registry.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Registry) > 0 {
		for iNdEx := len(m.Registry) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Registry[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryShowRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryShowRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Registry.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Registry) > 0 {
		for _, e := range m.Registry {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryShowRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Registry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registry = append(m.Registry, Registry{})
			if err := m.Registry[len(m.Registry)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
