// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overlock/crossplane/v1beta1/query.proto

package v1beta1

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryShowConfigurationRequest
type QueryShowConfigurationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryShowConfigurationRequest) Reset()         { *m = QueryShowConfigurationRequest{} }
func (m *QueryShowConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowConfigurationRequest) ProtoMessage()    {}
func (*QueryShowConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{0}
}
func (m *QueryShowConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowConfigurationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowConfigurationRequest.Merge(m, src)
}
func (m *QueryShowConfigurationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowConfigurationRequest proto.InternalMessageInfo

func (m *QueryShowConfigurationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryShowConfigurationResponse
type QueryShowConfigurationResponse struct {
	Configuration Configuration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration"`
}

func (m *QueryShowConfigurationResponse) Reset()         { *m = QueryShowConfigurationResponse{} }
func (m *QueryShowConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowConfigurationResponse) ProtoMessage()    {}
func (*QueryShowConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{1}
}
func (m *QueryShowConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowConfigurationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowConfigurationResponse.Merge(m, src)
}
func (m *QueryShowConfigurationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowConfigurationResponse proto.InternalMessageInfo

func (m *QueryShowConfigurationResponse) GetConfiguration() Configuration {
	if m != nil {
		return m.Configuration
	}
	return Configuration{}
}

// QueryListConfigurationRequest
type QueryListConfigurationRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Creator    string             `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *QueryListConfigurationRequest) Reset()         { *m = QueryListConfigurationRequest{} }
func (m *QueryListConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListConfigurationRequest) ProtoMessage()    {}
func (*QueryListConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{2}
}
func (m *QueryListConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListConfigurationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListConfigurationRequest.Merge(m, src)
}
func (m *QueryListConfigurationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListConfigurationRequest proto.InternalMessageInfo

func (m *QueryListConfigurationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryListConfigurationRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// QueryListConfigurationResponse
type QueryListConfigurationResponse struct {
	Configurations []Configuration     `protobuf:"bytes,1,rep,name=configurations,proto3" json:"configurations"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListConfigurationResponse) Reset()         { *m = QueryListConfigurationResponse{} }
func (m *QueryListConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListConfigurationResponse) ProtoMessage()    {}
func (*QueryListConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{3}
}
func (m *QueryListConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListConfigurationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListConfigurationResponse.Merge(m, src)
}
func (m *QueryListConfigurationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListConfigurationResponse proto.InternalMessageInfo

func (m *QueryListConfigurationResponse) GetConfigurations() []Configuration {
	if m != nil {
		return m.Configurations
	}
	return nil
}

func (m *QueryListConfigurationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryShowEnvironmentRequest
type QueryShowEnvironmentRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryShowEnvironmentRequest) Reset()         { *m = QueryShowEnvironmentRequest{} }
func (m *QueryShowEnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowEnvironmentRequest) ProtoMessage()    {}
func (*QueryShowEnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{4}
}
func (m *QueryShowEnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowEnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowEnvironmentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowEnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowEnvironmentRequest.Merge(m, src)
}
func (m *QueryShowEnvironmentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowEnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowEnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowEnvironmentRequest proto.InternalMessageInfo

func (m *QueryShowEnvironmentRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryShowEnvironmentResponse
type QueryShowEnvironmentResponse struct {
	Environment *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
}

func (m *QueryShowEnvironmentResponse) Reset()         { *m = QueryShowEnvironmentResponse{} }
func (m *QueryShowEnvironmentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowEnvironmentResponse) ProtoMessage()    {}
func (*QueryShowEnvironmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{5}
}
func (m *QueryShowEnvironmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowEnvironmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowEnvironmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowEnvironmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowEnvironmentResponse.Merge(m, src)
}
func (m *QueryShowEnvironmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowEnvironmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowEnvironmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowEnvironmentResponse proto.InternalMessageInfo

func (m *QueryShowEnvironmentResponse) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

// QueryListEnvironmentRequest
type QueryListEnvironmentRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Creator    string             `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *QueryListEnvironmentRequest) Reset()         { *m = QueryListEnvironmentRequest{} }
func (m *QueryListEnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListEnvironmentRequest) ProtoMessage()    {}
func (*QueryListEnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{6}
}
func (m *QueryListEnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListEnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListEnvironmentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListEnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListEnvironmentRequest.Merge(m, src)
}
func (m *QueryListEnvironmentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListEnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListEnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListEnvironmentRequest proto.InternalMessageInfo

func (m *QueryListEnvironmentRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryListEnvironmentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// QueryListEnvironmentResponse
type QueryListEnvironmentResponse struct {
	Environments []Environment       `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListEnvironmentResponse) Reset()         { *m = QueryListEnvironmentResponse{} }
func (m *QueryListEnvironmentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListEnvironmentResponse) ProtoMessage()    {}
func (*QueryListEnvironmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_837ee27eae247445, []int{7}
}
func (m *QueryListEnvironmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListEnvironmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListEnvironmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListEnvironmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListEnvironmentResponse.Merge(m, src)
}
func (m *QueryListEnvironmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListEnvironmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListEnvironmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListEnvironmentResponse proto.InternalMessageInfo

func (m *QueryListEnvironmentResponse) GetEnvironments() []Environment {
	if m != nil {
		return m.Environments
	}
	return nil
}

func (m *QueryListEnvironmentResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryShowConfigurationRequest)(nil), "overlock.crossplane.v1beta1.QueryShowConfigurationRequest")
	proto.RegisterType((*QueryShowConfigurationResponse)(nil), "overlock.crossplane.v1beta1.QueryShowConfigurationResponse")
	proto.RegisterType((*QueryListConfigurationRequest)(nil), "overlock.crossplane.v1beta1.QueryListConfigurationRequest")
	proto.RegisterType((*QueryListConfigurationResponse)(nil), "overlock.crossplane.v1beta1.QueryListConfigurationResponse")
	proto.RegisterType((*QueryShowEnvironmentRequest)(nil), "overlock.crossplane.v1beta1.QueryShowEnvironmentRequest")
	proto.RegisterType((*QueryShowEnvironmentResponse)(nil), "overlock.crossplane.v1beta1.QueryShowEnvironmentResponse")
	proto.RegisterType((*QueryListEnvironmentRequest)(nil), "overlock.crossplane.v1beta1.QueryListEnvironmentRequest")
	proto.RegisterType((*QueryListEnvironmentResponse)(nil), "overlock.crossplane.v1beta1.QueryListEnvironmentResponse")
}

func init() {
	proto.RegisterFile("overlock/crossplane/v1beta1/query.proto", fileDescriptor_837ee27eae247445)
}

var fileDescriptor_837ee27eae247445 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0xb3, 0x79, 0xfb, 0x16, 0xb1, 0x85, 0x56, 0x5d, 0x71, 0x88, 0xd2, 0x62, 0x22, 0x4b,
	0x90, 0x10, 0x35, 0x5e, 0x35, 0x70, 0xe0, 0xcf, 0xad, 0xa8, 0x20, 0x21, 0x0e, 0x60, 0x24, 0x84,
	0xb8, 0x54, 0x8e, 0xb3, 0x38, 0x0b, 0xc9, 0x4e, 0xea, 0x75, 0x12, 0x10, 0x42, 0xa8, 0x7c, 0x02,
	0x24, 0x3e, 0x0b, 0x17, 0x10, 0x17, 0xb8, 0xf4, 0x58, 0x89, 0x0b, 0x27, 0x84, 0x12, 0x3e, 0x08,
	0x8a, 0xbd, 0x49, 0xec, 0xc4, 0x36, 0x56, 0x04, 0x97, 0xc8, 0x49, 0x66, 0xc6, 0xbf, 0x67, 0x9e,
	0x99, 0x5d, 0x5c, 0x86, 0x3e, 0x73, 0xdb, 0x60, 0x3f, 0xa7, 0xb6, 0x0b, 0x52, 0x76, 0xdb, 0x96,
	0x60, 0xb4, 0xbf, 0xdb, 0x60, 0x9e, 0xb5, 0x4b, 0x0f, 0x7b, 0xcc, 0x7d, 0x69, 0x74, 0x5d, 0xf0,
	0x80, 0x6c, 0x4d, 0x02, 0x8d, 0x59, 0xa0, 0xa1, 0x02, 0x8b, 0x9b, 0x56, 0x87, 0x0b, 0xa0, 0xfe,
	0x67, 0x10, 0x5f, 0xac, 0xda, 0x20, 0x3b, 0x20, 0x69, 0xc3, 0x92, 0x2c, 0x28, 0x34, 0x2d, 0xdb,
	0xb5, 0x1c, 0x2e, 0x2c, 0x8f, 0x83, 0x50, 0xb1, 0xe7, 0x1c, 0x70, 0xc0, 0x7f, 0xa4, 0xe3, 0x27,
	0xf5, 0xeb, 0xb6, 0x03, 0xe0, 0xb4, 0x19, 0xb5, 0xba, 0x9c, 0x5a, 0x42, 0x80, 0xe7, 0xa7, 0x48,
	0xf5, 0x2f, 0x4d, 0x03, 0xb7, 0x41, 0x3c, 0xe5, 0x4e, 0xcf, 0x0d, 0xbf, 0xa4, 0x96, 0x96, 0xc0,
	0x44, 0x9f, 0xbb, 0x20, 0x3a, 0x4c, 0x78, 0x41, 0xb8, 0x4e, 0xf1, 0xf9, 0x07, 0x63, 0xea, 0x87,
	0x2d, 0x18, 0xdc, 0x0a, 0x97, 0x33, 0xd9, 0x61, 0x8f, 0x49, 0x8f, 0xac, 0xe3, 0x3c, 0x6f, 0x16,
	0x50, 0x09, 0x55, 0x56, 0xcc, 0x3c, 0x6f, 0xea, 0x2f, 0xb0, 0x96, 0x94, 0x20, 0xbb, 0x20, 0x24,
	0x23, 0x8f, 0xf0, 0xd9, 0x08, 0x98, 0x9f, 0xbc, 0x56, 0xaf, 0x1a, 0x29, 0xad, 0x35, 0x22, 0xa5,
	0xf6, 0x56, 0x8e, 0x7f, 0x5c, 0xc8, 0x99, 0xd1, 0x32, 0xfa, 0x11, 0x52, 0xac, 0xf7, 0xb8, 0xf4,
	0x62, 0x59, 0x6f, 0x63, 0x3c, 0x6b, 0xba, 0x7a, 0xed, 0x25, 0x23, 0x70, 0xc8, 0x18, 0x3b, 0x64,
	0x04, 0x56, 0x4f, 0x5e, 0x7a, 0xdf, 0x72, 0x98, 0xca, 0x35, 0x43, 0x99, 0xa4, 0x80, 0x4f, 0xd9,
	0x2e, 0xb3, 0x3c, 0x70, 0x0b, 0xf9, 0x12, 0xaa, 0x9c, 0x36, 0x27, 0x5f, 0xf5, 0xaf, 0x48, 0xc9,
	0x8f, 0x61, 0x50, 0xf2, 0x1f, 0xe3, 0xf5, 0x08, 0xb7, 0x2c, 0xa0, 0xd2, 0x7f, 0x4b, 0xe9, 0x9f,
	0xab, 0x43, 0xee, 0x44, 0xe4, 0xe5, 0x7d, 0x79, 0xe5, 0x3f, 0xca, 0x0b, 0xb0, 0xc2, 0xfa, 0xf4,
	0x1a, 0xde, 0x9a, 0x7a, 0xb8, 0x3f, 0x1b, 0x89, 0x24, 0xcb, 0x9f, 0xe1, 0xed, 0xf8, 0x70, 0xa5,
	0xf8, 0x2e, 0x5e, 0x0b, 0x0d, 0x96, 0xea, 0x7b, 0x25, 0x55, 0x6e, 0xb8, 0x4c, 0x38, 0x59, 0x7f,
	0xa3, 0xd0, 0xc6, 0xfd, 0x8d, 0x41, 0xfb, 0xf7, 0x0e, 0x7f, 0x42, 0x4a, 0xed, 0x02, 0x81, 0x52,
	0x6b, 0xe2, 0x33, 0x21, 0xe0, 0x89, 0xbb, 0x99, 0xe5, 0x2a, 0x6f, 0x23, 0x35, 0xfe, 0x9a, 0xb3,
	0xf5, 0xa3, 0x55, 0xfc, 0xbf, 0x4f, 0x4f, 0xbe, 0x20, 0xbc, 0xb9, 0xb0, 0xa3, 0xe4, 0x46, 0x2a,
	0x66, 0xea, 0x49, 0x50, 0xbc, 0xb9, 0x54, 0x6e, 0x00, 0xa9, 0x5f, 0x7d, 0xfb, 0xed, 0xd7, 0xfb,
	0xbc, 0x41, 0x76, 0x62, 0x0f, 0x34, 0xd9, 0x82, 0xc1, 0x41, 0x64, 0xda, 0xe9, 0x2b, 0xde, 0x7c,
	0x4d, 0x3e, 0x23, 0xbc, 0xb9, 0xb0, 0x69, 0x59, 0x44, 0x24, 0x1d, 0x11, 0x59, 0x44, 0x24, 0xae,
	0xb6, 0x4e, 0x7d, 0x11, 0x97, 0x49, 0x39, 0x56, 0x44, 0x9b, 0x4b, 0x2f, 0x2a, 0x82, 0x7c, 0x44,
	0x78, 0x63, 0x6e, 0x6b, 0xc8, 0xb5, 0x6c, 0x6d, 0x5c, 0x1c, 0xfe, 0xe2, 0xf5, 0x25, 0x32, 0x15,
	0x79, 0xdd, 0x27, 0xdf, 0x21, 0xd5, 0xe4, 0xf6, 0x87, 0x06, 0x32, 0x68, 0xfe, 0x07, 0x84, 0x37,
	0xe6, 0x96, 0x20, 0x0b, 0x7c, 0xfc, 0xe6, 0x66, 0x81, 0x4f, 0xd8, 0x38, 0xbd, 0xe6, 0xc3, 0x97,
	0xc9, 0xc5, 0xe4, 0xb6, 0x87, 0xe0, 0xf7, 0x0e, 0x8e, 0x87, 0x1a, 0x3a, 0x19, 0x6a, 0xe8, 0xe7,
	0x50, 0x43, 0xef, 0x46, 0x5a, 0xee, 0x64, 0xa4, 0xe5, 0xbe, 0x8f, 0xb4, 0xdc, 0x93, 0x7d, 0x87,
	0x7b, 0xad, 0x5e, 0xc3, 0xb0, 0xa1, 0x43, 0x07, 0xac, 0x51, 0x93, 0xac, 0xcf, 0xc4, 0xb4, 0x68,
	0x6d, 0x7c, 0x03, 0x3b, 0x40, 0x05, 0x34, 0x59, 0xda, 0xb5, 0xdb, 0x58, 0xf5, 0xaf, 0xce, 0x2b,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x54, 0x33, 0xa6, 0x55, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of ShowConfiguration items.
	ShowConfiguration(ctx context.Context, in *QueryShowConfigurationRequest, opts ...grpc.CallOption) (*QueryShowConfigurationResponse, error)
	// Queries a list of ListConfiguration items.
	ListConfiguration(ctx context.Context, in *QueryListConfigurationRequest, opts ...grpc.CallOption) (*QueryListConfigurationResponse, error)
	// Queries a list of ShowEnvironment items.
	ShowEnvironment(ctx context.Context, in *QueryShowEnvironmentRequest, opts ...grpc.CallOption) (*QueryShowEnvironmentResponse, error)
	// Queries a list of ListEnvironment items.
	ListEnvironment(ctx context.Context, in *QueryListEnvironmentRequest, opts ...grpc.CallOption) (*QueryListEnvironmentResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ShowConfiguration(ctx context.Context, in *QueryShowConfigurationRequest, opts ...grpc.CallOption) (*QueryShowConfigurationResponse, error) {
	out := new(QueryShowConfigurationResponse)
	err := c.cc.Invoke(ctx, "/overlock.crossplane.v1beta1.Query/ShowConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListConfiguration(ctx context.Context, in *QueryListConfigurationRequest, opts ...grpc.CallOption) (*QueryListConfigurationResponse, error) {
	out := new(QueryListConfigurationResponse)
	err := c.cc.Invoke(ctx, "/overlock.crossplane.v1beta1.Query/ListConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowEnvironment(ctx context.Context, in *QueryShowEnvironmentRequest, opts ...grpc.CallOption) (*QueryShowEnvironmentResponse, error) {
	out := new(QueryShowEnvironmentResponse)
	err := c.cc.Invoke(ctx, "/overlock.crossplane.v1beta1.Query/ShowEnvironment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListEnvironment(ctx context.Context, in *QueryListEnvironmentRequest, opts ...grpc.CallOption) (*QueryListEnvironmentResponse, error) {
	out := new(QueryListEnvironmentResponse)
	err := c.cc.Invoke(ctx, "/overlock.crossplane.v1beta1.Query/ListEnvironment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of ShowConfiguration items.
	ShowConfiguration(context.Context, *QueryShowConfigurationRequest) (*QueryShowConfigurationResponse, error)
	// Queries a list of ListConfiguration items.
	ListConfiguration(context.Context, *QueryListConfigurationRequest) (*QueryListConfigurationResponse, error)
	// Queries a list of ShowEnvironment items.
	ShowEnvironment(context.Context, *QueryShowEnvironmentRequest) (*QueryShowEnvironmentResponse, error)
	// Queries a list of ListEnvironment items.
	ListEnvironment(context.Context, *QueryListEnvironmentRequest) (*QueryListEnvironmentResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ShowConfiguration(ctx context.Context, req *QueryShowConfigurationRequest) (*QueryShowConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowConfiguration not implemented")
}
func (*UnimplementedQueryServer) ListConfiguration(ctx context.Context, req *QueryListConfigurationRequest) (*QueryListConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfiguration not implemented")
}
func (*UnimplementedQueryServer) ShowEnvironment(ctx context.Context, req *QueryShowEnvironmentRequest) (*QueryShowEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowEnvironment not implemented")
}
func (*UnimplementedQueryServer) ListEnvironment(ctx context.Context, req *QueryListEnvironmentRequest) (*QueryListEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnvironment not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ShowConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overlock.crossplane.v1beta1.Query/ShowConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowConfiguration(ctx, req.(*QueryShowConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overlock.crossplane.v1beta1.Query/ListConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListConfiguration(ctx, req.(*QueryListConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overlock.crossplane.v1beta1.Query/ShowEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowEnvironment(ctx, req.(*QueryShowEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/overlock.crossplane.v1beta1.Query/ListEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListEnvironment(ctx, req.(*QueryListEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "overlock.crossplane.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowConfiguration",
			Handler:    _Query_ShowConfiguration_Handler,
		},
		{
			MethodName: "ListConfiguration",
			Handler:    _Query_ListConfiguration_Handler,
		},
		{
			MethodName: "ShowEnvironment",
			Handler:    _Query_ShowEnvironment_Handler,
		},
		{
			MethodName: "ListEnvironment",
			Handler:    _Query_ListEnvironment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "overlock/crossplane/v1beta1/query.proto",
}

func (m *QueryShowConfigurationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowConfigurationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowConfigurationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowConfigurationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowConfigurationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowConfigurationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Configuration.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListConfigurationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListConfigurationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListConfigurationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListConfigurationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListConfigurationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListConfigurationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Configurations) > 0 {
		for iNdEx := len(m.Configurations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Configurations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowEnvironmentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowEnvironmentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowEnvironmentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowEnvironmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowEnvironmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowEnvironmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Environment != nil {
		{
			size, err := m.Environment.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListEnvironmentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListEnvironmentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListEnvironmentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListEnvironmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListEnvironmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListEnvironmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Environments) > 0 {
		for iNdEx := len(m.Environments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Environments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryShowConfigurationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryShowConfigurationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Configuration.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListConfigurationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListConfigurationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Configurations) > 0 {
		for _, e := range m.Configurations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowEnvironmentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryShowEnvironmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Environment != nil {
		l = m.Environment.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListEnvironmentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListEnvironmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Environments) > 0 {
		for _, e := range m.Environments {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryShowConfigurationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowConfigurationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowConfigurationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowConfigurationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowConfigurationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowConfigurationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Configuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Configuration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListConfigurationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListConfigurationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListConfigurationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListConfigurationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListConfigurationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListConfigurationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Configurations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Configurations = append(m.Configurations, Configuration{})
			if err := m.Configurations[len(m.Configurations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowEnvironmentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowEnvironmentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowEnvironmentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowEnvironmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowEnvironmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowEnvironmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Environment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Environment == nil {
				m.Environment = &Environment{}
			}
			if err := m.Environment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListEnvironmentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListEnvironmentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListEnvironmentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListEnvironmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListEnvironmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListEnvironmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Environments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Environments = append(m.Environments, Environment{})
			if err := m.Environments[len(m.Environments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
