// @generated
// This file is @generated by prost-build.
/// Metadata contains metadata information.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metadata {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub annotations: ::prost::alloc::string::String,
}
/// Configuration holds the configuration details.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Configuration {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(message, optional, tag="2")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(message, optional, tag="3")]
    pub spec: ::core::option::Option<ConfigurationSpec>,
    #[prost(string, tag="4")]
    pub creator: ::prost::alloc::string::String,
}
/// Spec defines the specification of the composition.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigurationSpec {
    #[prost(message, optional, tag="1")]
    pub crossplane: ::core::option::Option<CrossplaneSpec>,
    #[prost(string, tag="2")]
    pub package: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub aes_key: ::prost::alloc::string::String,
}
/// Crossplane specs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CrossplaneSpec {
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
}
/// Environment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Environment {
    /// metadata
    #[prost(message, optional, tag="1")]
    pub metadata: ::core::option::Option<Metadata>,
    /// id
    #[prost(uint64, tag="2")]
    pub id: u64,
    /// creator
    #[prost(string, tag="3")]
    pub creator: ::prost::alloc::string::String,
    /// provider
    #[prost(uint64, tag="4")]
    pub provider: u64,
}
/// Params defines the parameters for the module.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Params {
}
/// GenesisState defines the overlock module's genesis state.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// params defines all the parameters of the module.
    #[prost(message, optional, tag="1")]
    pub params: ::core::option::Option<Params>,
}
/// Provider
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Provider {
    /// metadata
    #[prost(message, optional, tag="1")]
    pub metadata: ::core::option::Option<Metadata>,
    /// id
    #[prost(uint64, tag="2")]
    pub id: u64,
    /// creator
    #[prost(string, tag="3")]
    pub creator: ::prost::alloc::string::String,
    /// ip
    #[prost(string, tag="4")]
    pub ip: ::prost::alloc::string::String,
    /// port
    #[prost(uint32, tag="5")]
    pub port: u32,
    /// country code
    #[prost(string, tag="6")]
    pub country_code: ::prost::alloc::string::String,
    /// environment type
    #[prost(string, tag="7")]
    pub environment_type: ::prost::alloc::string::String,
    /// availability
    #[prost(string, tag="8")]
    pub availability: ::prost::alloc::string::String,
    /// register time
    #[prost(message, optional, tag="9")]
    pub register_time: ::core::option::Option<::prost_types::Timestamp>,
}
/// QueryShowConfigurationRequest
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryShowConfigurationRequest {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// QueryShowConfigurationResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryShowConfigurationResponse {
    #[prost(message, optional, tag="1")]
    pub configuration: ::core::option::Option<Configuration>,
}
/// QueryListConfigurationRequest
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryListConfigurationRequest {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageRequest>,
    #[prost(string, tag="2")]
    pub creator: ::prost::alloc::string::String,
}
/// QueryListConfigurationResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryListConfigurationResponse {
    #[prost(message, repeated, tag="1")]
    pub configurations: ::prost::alloc::vec::Vec<Configuration>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageResponse>,
}
/// QueryShowEnvironmentRequest
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryShowEnvironmentRequest {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// QueryShowEnvironmentResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryShowEnvironmentResponse {
    #[prost(message, optional, tag="1")]
    pub environment: ::core::option::Option<Environment>,
}
/// QueryListEnvironmentRequest
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryListEnvironmentRequest {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageRequest>,
    #[prost(string, tag="2")]
    pub creator: ::prost::alloc::string::String,
}
/// QueryListEnvironmentResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryListEnvironmentResponse {
    #[prost(message, repeated, tag="1")]
    pub environments: ::prost::alloc::vec::Vec<Environment>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageResponse>,
}
/// QueryShowProviderRequest
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryShowProviderRequest {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// QueryShowProviderResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryShowProviderResponse {
    #[prost(message, optional, tag="1")]
    pub provider: ::core::option::Option<Provider>,
}
/// QueryListProviderRequest
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryListProviderRequest {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageRequest>,
    #[prost(message, optional, tag="2")]
    pub creator: ::core::option::Option<::prost::alloc::string::String>,
}
/// QueryListProviderResponse
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryListProviderResponse {
    #[prost(message, repeated, tag="1")]
    pub providers: ::prost::alloc::vec::Vec<Provider>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageResponse>,
}
/// MsgCreateConfiguration
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateConfiguration {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(message, optional, tag="5")]
    pub spec: ::core::option::Option<ConfigurationSpec>,
}
/// MsgCreateConfigurationResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgCreateConfigurationResponse {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// MsgUpdateConfiguration
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateConfiguration {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub id: u64,
    #[prost(message, optional, tag="5")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(message, optional, tag="6")]
    pub spec: ::core::option::Option<ConfigurationSpec>,
}
/// MsgUpdateConfigurationResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateConfigurationResponse {
}
/// MsgDeleteConfiguration
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgDeleteConfiguration {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub id: u64,
}
/// MsgDeleteConfigurationResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgDeleteConfigurationResponse {
}
/// MsgCreateEnvironment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateEnvironment {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(uint64, tag="4")]
    pub provider: u64,
}
/// MsgCreateEnvironmentResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgCreateEnvironmentResponse {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// MsgUpdateEnvironment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateEnvironment {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub id: u64,
    #[prost(message, optional, tag="3")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(uint64, tag="4")]
    pub provider: u64,
}
/// MsgUpdateEnvironmentResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateEnvironmentResponse {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// MsgDeleteEnvironment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgDeleteEnvironment {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub id: u64,
}
/// MsgDeleteEnvironmentResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgDeleteEnvironmentResponse {
}
/// MsgCreateProvider
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateProvider {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(string, tag="3")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub port: u32,
    #[prost(string, tag="5")]
    pub country_code: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub environment_type: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub availability: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub register_time: ::core::option::Option<::prost_types::Timestamp>,
}
/// MsgCreateProviderResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgCreateProviderResponse {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// MsgUpdateProvider
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateProvider {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub id: u64,
    #[prost(message, optional, tag="3")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(string, tag="4")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub port: u32,
    #[prost(string, tag="6")]
    pub country_code: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub environment_type: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub availability: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub register_time: ::core::option::Option<::prost_types::Timestamp>,
}
/// MsgUpdateProviderResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateProviderResponse {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
/// MsgDeleteProvider
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgDeleteProvider {
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub id: u64,
}
/// MsgDeleteProviderResponse
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgDeleteProviderResponse {
}
// @@protoc_insertion_point(module)
